### ISSUE TITLE
Documentation's typo

### ISSUE THREAD

**Issue by Insadem** [roblox-ts/roblox-ts.com#107]
In Roblox API category there's typo in event example. 
![IMG_20221125_233807.jpg](https://user-images.githubusercontent.com/92674256/204053467-11771284-bb6f-47c7-b88f-d53e65d157c1.jpg)

[Link](https://roblox-ts.com/docs/api/roblox-api).

**Comment by osyrisrblx** [comment]
Sorry, where's the typo?

**Comment by Insadem** [comment]
> Sorry, where's the typo?

Why first example with known type is okay, but second isn't? I thought you can't know type from remote event (as described in documentation).

**Comment by osyrisrblx** [comment]
The first is `OnClientEvent`, so the data comes from the server and you can trust it.

The second is `OnServerEvent`, so the data comes from the client. Clients can send whatever data they want, so you need to validate it first before using it.

**Comment by Insadem** [comment]
> Sorry, where's the typo?

Oh, sorry. Documentation were describing OnServerEvent and then in example OnClientEvent was shown. I didn't recognized difference at first
