### ISSUE TITLE
Missing Full Template for default.project.json

### ISSUE THREAD

**Issue by advra** [roblox-ts/roblox-ts.com#133]
The documentation on this [page](https://roblox-ts.com/docs/guides/syncing-with-rojo) provides a short example of default.project.json. It also gives a text link that says "[You can find the full version here.](https://github.com/roblox-ts/roblox-ts/blob/master/templates/game/default.project.json)" but when navigating for the full version it cannot be found.

Where can I get the full example?

**Comment by osyrisrblx** [comment]
Thanks for spotting this. I've merged a commit to fix this issue.

The file now lives [here](https://github.com/roblox-ts/create-roblox-ts/blob/master/templates/game/default.project.json).
